apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihypervisor.fullname" . }}-secrets
type: Opaque
data:
  postgres-user: {{ .Values.secrets.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  nats-user: {{ .Values.secrets.natsUser | b64enc | quote }}
  nats-password: {{ .Values.secrets.natsPassword | b64enc | quote }}
